### ISSUE TITLE
error

### ISSUE THREAD

**Issue by barca-cloud** [OIVAS7572/lichess-bot#104]
2021-09-02T03:12:35.803807+00:00 heroku[worker.1]: State changed from up to crashed
2021-09-02T04:03:41.441273+00:00 heroku[worker.1]: State changed from crashed to starting
2021-09-02T04:03:55.527023+00:00 heroku[worker.1]: Starting process with command `/bin/sh -c python3\ run.py`
2021-09-02T04:03:56.130737+00:00 heroku[worker.1]: State changed from starting to up
2021-09-02T04:03:57.078902+00:00 app[worker.1]:   File "//lichess-bot.py", line 246
2021-09-02T04:03:57.078921+00:00 app[worker.1]:     greeting_cfg = config.get("greeting", {} or {}
2021-09-02T04:03:57.078922+00:00 app[worker.1]: IndentationError: unexpected indent
2021-09-02T04:03:57.129501+00:00 heroku[worker.1]: Process exited with status 0
2021-09-02T04:03:57.290430+00:00 heroku[worker.1]: State changed from up to crashed
2021-09-02T04:58:31.000000+00:00 app[api]: Build started by user sff3ecc@gmail.com
2021-09-02T05:01:47.837007+00:00 heroku[worker.1]: State changed from crashed to starting
2021-09-02T05:01:47.415896+00:00 app[api]: Deploy b374ab88 by user sff3ecc@gmail.com
2021-09-02T05:01:47.000000+00:00 app[api]: Build succeeded
2021-09-02T05:01:47.415896+00:00 app[api]: Release v11 created by user sff3ecc@gmail.com
2021-09-02T05:01:59.833945+00:00 heroku[worker.1]: Starting process with command `/bin/sh -c python3\ run.py`
2021-09-02T05:02:00.498299+00:00 heroku[worker.1]: State changed from starting to up
2021-09-02T05:02:01.579617+00:00 app[worker.1]:   File "//lichess-bot.py", line 246
2021-09-02T05:02:01.579628+00:00 app[worker.1]:     greeting_cfg = config.get("greeting", {} or {}
2021-09-02T05:02:01.579628+00:00 app[worker.1]: IndentationError: unexpected indent
2021-09-02T05:02:01.651490+00:00 heroku[worker.1]: Process exited with status 0
2021-09-02T05:02:01.755722+00:00 heroku[worker.1]: State changed from up to crashed
2021-09-02T05:02:01.761086+00:00 heroku[worker.1]: State changed from crashed to starting
2021-09-02T05:02:13.196246+00:00 heroku[worker.1]: Starting process with command `/bin/sh -c python3\ run.py`
2021-09-02T05:02:13.880421+00:00 heroku[worker.1]: State changed from starting to up
2021-09-02T05:02:15.737170+00:00 heroku[worker.1]: Process exited with status 0
2021-09-02T05:02:15.884832+00:00 heroku[worker.1]: State changed from up to crashed
2021-09-02T05:02:15.684248+00:00 app[worker.1]:   File "//lichess-bot.py", line 246
2021-09-02T05:02:15.684267+00:00 app[worker.1]:     greeting_cfg = config.get("greeting", {} or {}
2021-09-02T05:02:15.684268+00:00 app[worker.1]: IndentationError: unexpected indent

**Comment by OIVAS7572** [comment]
What changes you made?
can you send me your repo link

**Comment by barca-cloud** [comment]
@OIVAS7572 it a private repo https://github.com/barca-cloud/thechessbot here . I changed as u told me in bot message

**Comment by barca-cloud** [comment]
it now shows thsi
2021-09-02T06:36:42.794134+00:00 heroku[worker.1]: State changed from starting to up
2021-09-02T06:36:44.411722+00:00 app[worker.1]: Traceback (most recent call last):
2021-09-02T06:36:44.411737+00:00 app[worker.1]:   File "//lichess-bot.py", line 18, in <module>
2021-09-02T06:36:44.411842+00:00 app[worker.1]:     from conversation import Conversation, ChatLine
2021-09-02T06:36:44.411845+00:00 app[worker.1]:   File "/conversation.py", line 48
2021-09-02T06:36:44.411846+00:00 app[worker.1]:     self.send_reply(ChatLine({"room": room}), message)
2021-09-02T06:36:44.411860+00:00 app[worker.1]:     ^
2021-09-02T06:36:44.411861+00:00 app[worker.1]: IndentationError: expected an indented block
2021-09-02T06:36:44.482572+00:00 heroku[worker.1]: Process exited with status 0
2021-09-02T06:36:44.585625+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by barca-cloud** [comment]
****pls help

**Comment by RandomInventor** [comment]
@barca-cloud you can use my code for welcome messages letme know if it works https://github.com/RandomInventor/lichess-bot

**Comment by RandomInventor** [comment]
If https://github.com/barca-cloud/thechessbot is a private repo we cannot help also this repo's issues are for https://github.com/OIVAS7572/lichess-bot not for https://github.com/barca-cloud/thechessbot or others wait till the owners implement this or you can fix or make this https://github.com/barca-cloud/thechessbot a puplic repo so that we can help

**Comment by barca-cloud** [comment]
Well @RandomInventor  once very long time ago i add a bot but the repo was ...... what do i say public and token got hacked and the bot started to play worse and i have to close account.

**Comment by barca-cloud** [comment]
Btw @OIVAS7572 you are added in this repo so you can see the repo

**Comment by RandomInventor** [comment]
lol @barca-cloud he may able to see the token

**Comment by barca-cloud** [comment]
@RandomInventor  @OIVAS7572 is a good guy so maybe he wont mess up anyhting btw @RandomInventor i can add you

**Comment by RandomInventor** [comment]
no need

**Comment by OIVAS7572** [comment]
@barca-cloud 
Try deploying new branch created by me

**Comment by barca-cloud** [comment]
@OIVAS7572  did not saw that but i am busy today maybe i do tommorow.  Almmm

**Comment by barca-cloud** [comment]
@OIVAS7572 i am deploying ur new branch

**Comment by barca-cloud** [comment]
@OIVAS7572 it got conected yaya

**Comment by barca-cloud** [comment]
hmm but the bot dont send a messages at starting

**Comment by barca-cloud** [comment]
or good bye.
