### ISSUE TITLE
The Bot is not coming online.

### ISSUE THREAD

**Issue by SathyaKarthik1212** [OIVAS7572/lichess-bot#30]
I made a lc0 bot with lc0 engine but it is not coming . I used https://github.com/OIVAS7572/lichess-bot/tree/lczero . When i turn on worker, even though it is not coming.

```
    .   _/|
    .  // o\
    .  || ._)  lichess-bot 1.2.0
    .  //__\
    .  )___(   Play on Lichess with a bot

Backing off api_get(...) for 0.1s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='lichess.org', port=443): Max retries exceeded with url: /api/account (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc95f7d3f60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Backing off api_get(...) for 0.0s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='lichess.org', port=443): Max retries exceeded with url: /api/account (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc95f7d3c18>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Backing off api_get(...) for 0.0s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='lichess.org', port=443): Max retries exceeded with url: /api/account (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc95f7d3fd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Backing off api_get(...) for 0.1s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='lichess.org', port=443): Max retries exceeded with url: /api/account (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc95f7d3f28>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Backing off api_get(...) for 0.0s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='lichess.org', port=443): Max retries exceeded with url: /api/account (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc95f7d3e80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Backing off api_get(...) for 0.0s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='lichess.org', port=443): Max retries exceeded with url: /api/account (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc95f7d34e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Backing off api_get(...) for 0.0s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='lichess.org', port=443): Max retries exceeded with url: /api/account (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc95f7d36a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Backing off api_get(...) for 0.1s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='lichess.org', port=443): Max retries exceeded with url: /api/account (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc95f7d3a20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Giving up api_get(...) after 9 tries (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='lichess.org', port=443): Max retries exceeded with url: /api/account (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc95f7d3d68>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fc95f7d3d68>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='lichess.org', port=443): Max retries exceeded with url: /api/account (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc95f7d3d68>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lichess-bot.py", line 440, in <module>
    user_profile = li.get_profile()
  File "/lichess.py", line 92, in get_profile
    profile = self.api_get(ENDPOINTS["profile"])
  File "/usr/local/lib/python3.7/dist-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/lichess.py", line 46, in api_get
    response = self.session.get(url, timeout=2)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='lichess.org', port=443): Max retries exceeded with url: /api/account (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc95f7d3d68>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

**Comment by TheYoBots** [comment]
As per the logs here, your profile wasn’t got. This means that either your token doesn’t have `bot:play` scopes or your account has already played games and it couldn’t be upgraded to a bot account.

**Comment by OIVAS7572** [comment]
@SathyaKarthik1212 
Thanks For Trying to test Lc0

**Comment by SathyaKarthik1212** [comment]
@TheYoBots but i included all and i was not getting to click board:play option so i left it and clicked all others.

@OIVAS7572 How to fix it.

**Comment by TheYoBots** [comment]
@SathyaKarthik1212 You’ve either have lichess’ rate limits somehow or your token might have a problem. Try creating a new token and in that token only select `bot:play` scopes, nothing else.

**Comment by SathyaKarthik1212** [comment]
OK @TheYoBots

**Comment by SathyaKarthik1212** [comment]
@TheYoBots i tried the same it turned into bot and it is coming online but not playing moves.

**Comment by TheYoBots** [comment]
Send the error logs please, I’ll check it out

**Comment by SathyaKarthik1212** [comment]
Making it stockfish. Thanks for your help @OIVAS7572  and @TheYoBots . Thanks.
